project_id = "rizftvjircbgfsamrvdf"

[functions.eventbrite-search]
verify_jwt = true

[functions.google-calendar-auth]
verify_jwt = true

[functions.google-calendar-callback]
verify_jwt = false

[functions.google-calendar-fetch]
verify_jwt = true

[functions.send-ride-invite]
verify_jwt = true

[functions.send-ride-notification]
verify_jwt = true

[functions.send-attendance-survey]
verify_jwt = false

[functions.process-attendance-consensus]
verify_jwt = false