project_id = "rizftvjircbgfsamrvdf"

[functions.eventbrite-search]
verify_jwt = true

[functions.google-calendar-auth]
verify_jwt = false

[functions.google-calendar-callback]
verify_jwt = false

[functions.google-calendar-fetch]
verify_jwt = true